version: '3.8'

services: 
  occv:
    build: .
    volumes: 
      - .:/code
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
      - CERT_COUNTRY=DE
    ports: 
      - "8000:8000"
    container_name: "occv" 
    command: uvicorn occv:app --reload --host=0.0.0.0 --port=8000