version: '3.8'

services: 
  occv:
    image: ghcr.io/av_jui/open-covid-certificate-validator:main
    volumes: 
      - ./data:/code/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
      - CERT_COUNTRY=DE
    ports: 
      - "8181:8000"
    container_name: "occv" 